### ISSUE TITLE
I'll help

### ISSUE THREAD

**Issue by Kyrotechnic** [valekatoz/Kore#1]
I have my old Skyblock Client that I could give you the source code of if you'd like.

It has like 50 modules, a modern click gui, etc.

Let me know by responding to this issue! Also, I'll help maintain and add features accordingly if so.

**Comment by valekatoz** [comment]
> I have my old Skyblock Client that I could give you the source code of if you'd like.
> 
> 
> 
> It has like 50 modules, a modern click gui, etc.
> 
> 
> 
> Let me know by responding to this issue! Also, I'll help maintain and add features accordingly if so.

Hello, I would like to check it out if i can, my discord is "vk#6082"

**Comment by Kyrotechnic** [comment]
Hello, sorry, I do not have discord. However, I will send you the github repo.

https://github.com/Kyrotechnic/KyroClient

**Comment by valekatoz** [comment]
Your client does not appear to be working... anything i try to run crashes (i tried running on my vm), i also noticed your "k_1.8.9-forge.jar" is obfuscated, why is that?

**Comment by Kyrotechnic** [comment]
It is not currently possible to run it without the custom profile due to not using a @Mod annotation

**Comment by valekatoz** [comment]
> It is not currently possible to run it without the custom profile due to not using a @mod annotation

[09:47:51] [main/INFO]: Calling tweak class me.kyroclient.tweaker.Tweaker
[09:47:51] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap

It crashes, i am using "SKLauncher 3.2" if that helps you.

**Comment by Kyrotechnic** [comment]
Sorry for the delay in my reply! Please use a mod in your mods folder that has the Mixin Library. Skytils works if you have that.

**Comment by valekatoz** [comment]
> Sorry for the delay in my reply! Please use a mod in your mods folder that has the Mixin Library. Skytils works if you have that.
> 
> Edit for explanation: Forge tweaker runs first, which adds the mods into the classpath. Then, my tweaker runs with all those in classpath. Skytils has the dependency in its jar so it then works.

I still have this issue. I installed skytils in my mods folder, i get the same exact error.

[08:46:44] [main/INFO]: Loading tweaker gg.skytils.skytilsmod.tweaker.SkytilsTweaker from Skytils-1.7.9.jar
[08:46:44] [main/INFO]: Calling tweak class me.kyroclient.tweaker.Tweaker
[08:46:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap

**Comment by Kyrotechnic** [comment]
Sure can do! Give me just a few minutes. Also, I'll fix the issue in an update eventually.

Also, the way this client works is that the mod loads at runtime, auto updating every time you run your game.

![image](https://github.com/valekatoz/Kore/assets/141758940/6509c00e-30aa-4924-9edf-b3415f02f095)
![image](https://github.com/valekatoz/Kore/assets/141758940/c0fb75d4-eb1f-4717-b782-1d396fed2078)
![image](https://github.com/valekatoz/Kore/assets/141758940/f8801ff5-561f-4f41-9b6e-621b616ec317)

**Comment by valekatoz** [comment]
It looks really good, you made the ClickGui yourself?

**Comment by Kyrotechnic** [comment]
Indeed I did. So, what do you say? Merge clients?

**Comment by Kyrotechnic** [comment]
Also, It'd be easier to message on this [irc](https://chat.irc.net/irc.net/%23koreclient)

**Comment by valekatoz** [comment]
> Also, It'd be easier to message on this [irc](https://chat.irc.net/irc.net/%23koreclient)

I belive i joined the koreclient channel

> Indeed I did. So, what do you say? Merge clients?

I really like the clickgui, but as of right now your client seems a bit messy, it is just my tought tho... also i like it more if this was just a mod, rather than a whole client.

So, to answer your question, yes, but slowly and done efficiently, i would start by importing your clickgui to kore, and then work on all the features.

May i also ask, what is your end goal for this?

**Comment by Kyrotechnic** [comment]
My end goal is to provide a free and open source alternative to oringo client and other paid clients.

Also, development has been fun. My client is indeed a mess, but it's semi well put together. Also, some of my features are a bit of a mess.

**Comment by valekatoz** [comment]
> My end goal is to provide a free and open source alternative to oringo client and other paid clients.
> 
> Also, development has been fun. My client is indeed a mess, but it's semi well put together. Also, some of my features are a bit of a mess.

As soon as i have some free time i will try to import the clickgui. Also, i don't know if you haven't typed anything yet but i do not see your messages in the IRC

**Comment by Kyrotechnic** [comment]
Alright. Then, is it alright if we use revolt? I can't seem to get the IRC to work.

**Comment by valekatoz** [comment]
> Alright. Then, is it alright if we use revolt? I can't seem to get the IRC to work.
> 
> Edit: if so, my name is Ky#8820

Sorry for the late reply, sure, i sent you a friend request.
